services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Wexample\SymfonyForms\:
        resource: '../../{Service,Twig,Controller}'

    Wexample\SymfonyForms\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']
